use gagnesh;

-- Easy
CREATE TABLE Employee2 (
    EmpID INT ,
   
);
INSERT INTO Employee2 (EmpID) 
VALUES (2), (4 ), (4), (6), (6), (7), (8), (8);

Select Max(EmpID) as [Maximum ID] from (Select EmpID from Employee2 Group by EmpID having Count(*) < 2)as Subquery;

--Medium

 CREATE TABLE TBL_PRODUCTS
(
	ID INT PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(50),
	[DESCRIPTION] NVARCHAR(250) 
)

CREATE TABLE TBL_PRODUCTSALES
(
	ID INT PRIMARY KEY IDENTITY,
	PRODUCTID INT FOREIGN KEY REFERENCES TBL_PRODUCTS(ID),
	UNITPRICE INT,
	QUALTITYSOLD INT
)

INSERT INTO TBL_PRODUCTS VALUES ('TV','52 INCH BLACK COLOR LCD TV')
INSERT INTO TBL_PRODUCTS VALUES ('LAPTOP','VERY THIIN BLACK COLOR ACER LAPTOP')
INSERT INTO TBL_PRODUCTS VALUES ('DESKTOP','HP HIGH PERFORMANCE DESKTOP')


INSERT INTO TBL_PRODUCTSALES VALUES (3,450,5)
INSERT INTO TBL_PRODUCTSALES VALUES (2,250,7)
INSERT INTO TBL_PRODUCTSALES VALUES (3,450,4)
INSERT INTO TBL_PRODUCTSALES VALUES (3,450,9)


SELECT *FROM TBL_PRODUCTS
SELECT *FROM TBL_PRODUCTSALES

Select [ID],[NAME],[DESCRIPTION] from TBL_PRODUCTS where ID not in (Select Distinct PRODUCTID from TBL_PRODUCTSALES);


SELECT 
    e.NAME AS [Product name],
    ISNULL((SELECT SUM(b.QUALTITYSOLD) 
            FROM TBL_PRODUCTSALES AS b 
            WHERE b.PRODUCTID = e.ID), 0) AS TotalQuantitySold
FROM TBL_PRODUCTS AS e;